# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BlockTutorial' do

  pod 'PDSSetting_objc', :git => 'https://github.com/w91379137/PDSSetting_objc.git'

  target 'BlockTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
